/*
 * This source file was generated by the Gradle 'init' task
 */
package org.loadtest.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
    @Test void testApp() {
        assertEquals(1, 1);
    }
}
